cs50-w/2-commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'
urlpatterns = [
    # Views
    path("", views.index, name="index"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category, name="category"),
    path("list", views.list, name="list"),
    path("listings/<int:auction_id>", views.listings, name="listings"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watchlist/<int:user_id>", views.watchlist, name="watchlist"),
    # Helper views (functions)
    path("helper/listings/1/<int:auction_id>", views.helper_auction_state, name="helper_auction_state"),
    path("helper/listings/2/<int:auction_id>", views.helper_post_comment, name="helper_post_comment"),
    path("helper/listings/3/<int:auction_id>", views.helper_watchlist, name="helper_watchlist")
]

cs50-w/2-commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

cs50-w/2-commerce/auctions/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices
from djmoney.models.fields import MoneyField
from django.utils import timezone


class Auction(models.Model):
    categories = models.ManyToManyField('Category')
    description = models.CharField(max_length=200)
    image_url = models.URLField(
        default="https://www.sinrumbofijo.com/wp-content/uploads/2016/05/default-placeholder.png")
    pub_date = models.DateTimeField(default=timezone.now)
    state = models.BooleanField(default=True)
    title = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, null=True, related_name='owner')

    def __str__(self):
        return self.title
    
    def current_bid(self):
        return self.bids.order_by('-amount')[0]
    
    def starting_bid(self):
        return self.bids.order_by('amount')[0]

    def bids_number(self):
        if self.bids.count() == 0:
            return 0
        if self.bids.count() == 1:
            return 1
        return 2
    
    
class Bid(models.Model):
    auction = models.ForeignKey('Auction', on_delete=CASCADE, null=True, related_name='bids')
    amount = MoneyField(max_digits=10, decimal_places=2)
    pub_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, null=True)
    
    def __str__(self):
        return '%s %s' % (self.amount, self.amount_currency)
    
    
class Category(models.Model):
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.category


class Comment(models.Model):
    auction = models.ForeignKey('Auction', on_delete=CASCADE, null=True, related_name="comments")
    comment = models.CharField(max_length=300)
    pub_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, null=True)

    def __str__(self):
        return self.comment
    

class User(AbstractUser):
    watchlist = models.ManyToManyField('Auction', related_name='listings')
    
    def __str__(self):
        return self.username

cs50-w/2-commerce/auctions/forms.py
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple, TextInput
from .models import Auction, Category, Comment, Bid
from django.forms import ModelForm, Textarea
from django.forms.utils import ErrorList


class MyCheckboxSelectMultiple(CheckboxSelectMultiple):
    
    pass


class DivErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self:
            return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<div class="alert alert-danger" role="alert">%s</div>' % e for e in self])


class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = [
            'categories', 
            'description',
            'image_url',
            'title', 
        ]
        widgets = {
            'description': Textarea(attrs={'cols': 40, 'rows': 3}), 
            'categories': CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(AuctionForm, self).__init__(*args, **kwargs)
        self.fields['categories'].queryset = Category.objects.order_by(
            'category')
        
        
class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['amount']
            

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {
            'comment': ''
        }
        widgets = {
            'comment': Textarea(attrs={'placeholder': 'Write a comment...',
                                       'rows': 1,
                                       'cols': 40})
        }
        

cs50-w/2-commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import AuctionForm, BidForm, CommentForm
from .models import Auction, Bid, Category, Comment, User


""" Views """

def categories(request):
    # Get all categories
    categories = Category.objects.all().order_by('category')
    return render(request, "auctions/categories.html", {
        "categories": categories
    })


def category(request, category_id):
    # Get all listings related to a category
    category = Category.objects.get(pk=category_id)
    listings = category.auction_set.all()
    return render(request, "auctions/category.html", {
        "category": category, 
        "listings": listings
    })
    

def index(request):
    # Get all auctions with a state=True and order them by pub_date
    return render(request, "auctions/index.html", {
        "auctions": Auction.objects.filter(state=True).order_by('-pub_date')
    })


def list(request):
    if request.method == "POST":
        
        # Create new auction and new bid
        auction_form = AuctionForm(request.POST)
        bid_form = BidForm(request.POST)
        if auction_form.is_valid() and bid_form.is_valid():
        
            # Create new auction
            new_auction = auction_form.save(commit=False)
            new_auction.user = request.user
            new_auction.save()
                    
            # Create new bid
            new_bid = bid_form.save(commit=False)
            new_bid.auction = new_auction
            new_bid.user = request.user
            new_bid.save()
            
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            # Return the submited form
            return render(request, "auctions/list.html", {
                "auction_form": auction_form, 
                "bid_form": bid_form
            })

    else:
        return render(request, "auctions/list.html", {
            "auction_form": AuctionForm(),
            "bid_form": BidForm()
        })


def listings(request, auction_id):
    error_messages = []
    listing = Auction.objects.get(pk=auction_id)
    user_watchlist = None
    if request.user.is_authenticated:
        user_watchlist = User.objects.get(pk=request.user.id).watchlist.all()
    
    if request.method == "POST":
        bid_form = BidForm(request.POST)      
        # Validate the bid_form  
        if bid_form.is_valid():
            new_bid = bid_form.save(commit=False)
            if listing.bids_number() == 1:
                if new_bid.amount >= listing.current_bid().amount:
                    new_bid.user = request.user
                    new_bid.auction = listing
                    new_bid.save()
                    return HttpResponseRedirect(reverse("auctions:listings", args=[auction_id]))
                else:
                    error_messages.append("Your bid must be at least equal to the starting bid!")
            else:
                if new_bid.amount >= listing.current_bid().amount:
                    new_bid.user = request.user
                    new_bid.auction = listing
                    new_bid.save()
                    return HttpResponseRedirect(reverse("auctions:listings", args=[auction_id]))
                else:
                    error_messages.append("Your bid must be higher than the current bid!")

    return render(request, "auctions/listings.html", {
        "bid_form": BidForm(),
        "comment_form": CommentForm(),
        "comments": listing.comments.order_by('-pub_date'),
        "error_messages": error_messages,
        "listing": listing,
        "user_watchlist": user_watchlist
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="/login/")
def watchlist(request, user_id):
    user_watchlist = User.objects.get(pk=request.user.id).watchlist.all()
    
    return render(request, "auctions/watchlist.html", {
        "user_watchlist": user_watchlist
    })
    

""" Helper functions """

def helper_auction_state(request, auction_id):
    """
    Close or reopen an auction
    """
    auction = Auction.objects.get(pk=auction_id)
    auction.state = not auction.state
    auction.save()
    
    return HttpResponseRedirect(reverse("auctions:listings", args=[auction_id]))

        
def helper_post_comment(request, auction_id):
    """
    Post comment
    """
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.auction = Auction.objects.get(pk=auction_id)
            new_comment.user = request.user
            new_comment.save()
    return HttpResponseRedirect(reverse("auctions:listings", args=[auction_id]))


def helper_watchlist(request, auction_id):
    """
    Add or remove auction from watchlist
    """
    watchlist = User.objects.get(pk=request.user.id).watchlist
    auction = Auction.objects.get(pk=auction_id)
    if auction in watchlist.all():
        watchlist.remove(auction)
    else:
        watchlist.add(auction)
    return HttpResponseRedirect(reverse("auctions:listings", args=[auction_id]))
        



    

cs50-w/2-commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-center p-2 m-2">Categories</h2>

<div class="text-center p-2 m-2">
    {% for category in categories %}
    <a class="btn btn-dark p-3 m-1" href="{% url 'auctions:category' category.id %}">{{ category.category }}</a>
    {% endfor %}
</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% load static %}


{% block body %}

<h2 class="text-center p-2 m-2">{{ category.category }}</h2>

<div class="d-flex flex-wrap justify-content-center">

    {% for listing in listings %}
    <div class="card m-3" style="width: 19rem">

        <a href="{% url 'auctions:listings' listing.id %}">
            <img class="card-img-top" src="{{ listing.image_url }}" width="500px">
        </a>

        <div class="card-body m-2">

            <h3>{{ listing.title }}</h3>
            <div class="card-text">
                <p>{{ listing.description }}</p>
                {% if listing.bids_number == 1 %}
                <p>Starting bid: {{ listing.starting_bid }}</p>
                {% else %}
                <p>Current bid: {{ listing.current_bid }}</p>
                {% endif %}
                <p class="blockquote-footer">Published by: {{ listing.user.username }}</p>
                <p class="blockquote-footer">Publication date: {{ listing.pub_date }}</p>
            </div>
        </div>

    </div>
    {% endfor %}

</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-center p-2 m-2">Active Listings</h2>

<div class="d-flex flex-wrap justify-content-center">

	{% for auction in auctions %}
	<div class="card m-3" style="width: 19rem;">

		<a href="{% url 'auctions:listings' auction.id %}">
			<img class="card-img-top" src="{{ auction.image_url }}" width="500px">
		</a>

		<div class="card-body m-2">
			<h3>{{ auction.title }}</h3>

			<div class="card-text">
				<p>{{ auction.description }}</p>
				{% if auction.bids_number == 1 %}
				<p>Starting bid: {{ auction.starting_bid }}</p>
				{% else %}
				<p>Current bid: {{ auction.current_bid }}</p>
				{% endif %}
				<p class="blockquote-footer">Published by: {{ auction.user.username }}</p>
				<p class="blockquote-footer">{{ auction.pub_date }}</p>
			</div>
		</div>

	</div>
	{% endfor %}

</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        {% block title %}
        Auctions
        {% endblock %}
    </title>
    <!--Styling-->
    <link href="https://fonts.googleapis.com/css2?family=Spline+Sans:wght@400;500;600;700&display=swap"
        rel="stylesheet">
    <!--BootstrapCSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'auctions/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet" />

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light text-center">
        <div class="container d-flex justify-content-center">
            <a class="navbar-brand" href="#">
                <img src="{% static "auctions/images/auctions-icon-brand.png" %}" alt="" width="25" height="25"
                    class="mx-2">
                <strong>Auctions</strong>
            </a>
            <div class="nav-item">
                <a class="nav-link" href="#">
                    {% if user.is_authenticated %}
                    Welcome <strong>{{ user.username }}</strong>!
                    {% else %}
                    Not signed in
                    {% endif %}
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:list' %}">Create Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:watchlist' user.id %}">Watchlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <!-- BootstrapJS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

</body>

</html>

cs50-w/2-commerce/auctions/templates/auctions/list.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-center m-3">Create Listing</h2>

<form class="text-center my-2" action='{% url 'auctions:list' %}' method='post'>
    {% csrf_token %}
    <!--Auction's Title-->
    <div class="form-group m-1">
        <div>{{ auction_form.title.errors }}</div>
        <div><label for="{{ auction_form.title.id_for_label }}"><strong>Title:</strong></label></div>
        <div>{{ auction_form.title }}</div>
    </div>
    <!--Auction's Category-->
    <div class="form-group m-1">
        <div>{{ auction_form.categories.errors }}</div>
        <div><label for="{{ auction_form.categories.id_for_label }}"><strong>Categories:</strong></label></div>
        <div>{{ auction_form.categories }}</div>
    </div>
    <!--Auction's Image-->
    <div class="form-group m-1">
        <div>{{ auction_form.image_url.errors }}</div>
        <div> <label for="{{ auction_form.image_url.id_for_label }}"><strong>Image URL:</strong></label></div>
        <div>{{ auction_form.image_url }}</div>
    </div>
    <!--Auction's Description-->
    <div class="form-group m-1">
        <div>{{ auction_form.description.errors }}</div>
        <div><label for="{{ auction_form.description.id_for_label }}"><strong>Description:</strong></label></div>
        <div>{{ auction_form.description }}</div>
    </div>
    <!--Auction's Bid-->
    <div class="form-group m-1">
        <div>{{ bid_form.amount.errors }}</div>
        <div><label for="{{ bid_form.amount.id_for_label }}"><strong>Starting bid:</strong></label></div>
        <div>{{ bid_form.amount }}</div>

    </div>
    <input class="btn btn-dark m-1" type="submit" value="Post">
</form>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/listings.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

{% for error_message in error_messages %}
<div class="alert alert-danger text-center" role="alert">
	{{ error_message }}
</div>
{% endfor %}

<!--Auction's title-->
<h2 class="text-center p-2 m-2">{{ listing.title }}</h2>
<!--Action's options-->
{% if user.is_authenticated %}

<div class="text-center p-2 m-2">
	<!--Watchlist (Add or Remove)-->
	{% if listing in user_watchlist %}
	<a class="btn btn-outline-dark" href="{% url 'auctions:helper_watchlist' listing.id %}">Remove from Watchlist</a>
	{% elif listing not in user_watchlist%}
	<a class="btn btn-outline-dark" href="{% url 'auctions:helper_watchlist' listing.id %}">Add to Watchlist</a>
	{% endif %}
	<!--Auction's state (Close or Open)-->
	{% if listing.state and listing.user == user %}
	<a class="btn btn-outline-dark" href="{% url 'auctions:helper_auction_state' listing.id %}">Close Auction</a>
	{% elif not listing.state and listing.user == user %}
	<a class="btn btn-outline-dark" href="{% url 'auctions:helper_auction_state' listing.id %}">Reopen Auction</a>
	{% endif %}
	<!--Display winner-->
	{% if not listing.state and listing.current_bid.user == user %}
	<div class="alert alert-success p-2 m-2">You won!</div>
	{% endif %}
</div>

{% endif %}

<!--Auction's description-->
<div class="container d-flex flex-wrap justify-content-center align-content-center">
	<!--Auction's image-->
	<div class="m-2">
		<img id="auction-image" src="{{ listing.image_url }}" />
	</div>
	<!--Auction's details-->
	<div class="text-center" id="auction-details">
		<!--Auction's title-->
		<div>
			<p>{{ listing.description }}</p>
		</div>
		<!--Auction's bids-->
		<div>
			{% if listing.bids_number == 1 %}
			<p>Starting bid: {{ listing.starting_bid }}</p>
			{% else %}
			<p>Current bid: {{ listing.current_bid }}</p>
			{% endif %}
			<p class="text-muted">Published by: {{ listing.user.username }}</p>
			<p class="text-muted">Publication date: {{ listing.pub_date }}</p>
		</div>
		<!--Auction's bid form-->
		<div>
			{% if user.is_authenticated%}
			<form action="{% url 'auctions:listings' listing.id %}" method="post">
				{% csrf_token %}
				<div class="m-2">{{ bid_form.amount }}</div>
				<div class="m-1"><input class="btn btn-outline-dark" type="submit" value="Place Bid" /></div>
			</form>
			{% endif %}
		</div>
	</div>
</div>

<!--Comments view-->
<!--Comment form-->
<hr>
<div style="margin: auto;">
	{% if user.is_authenticated%}
	<form class="text-center m-3" action="{% url 'auctions:helper_post_comment' listing.id %}" method="post">
		{% csrf_token %}
		<div>
			{{ comment_form }}
		</div>
		<div>
			<input class="btn btn-dark" type="submit" value="Post" />
		</div>
	</form>
	{% endif %}

	<!-- Display comments -->
	<div class="container">
		{% for comment in comments %}
		<div class="card">
			<div class="card-body">
				<div><strong>{{ comment.user.username }}</strong></div>
				<div>{{ comment.comment }}</div>
				<div class="text-muted">{{ comment.pub_date }}</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<div class="text-center m-3">
  <h2>Login</h2>
</div>

{% if message %}
<div class="text-center m-2">{{ message }}</div>
{% endif %}

<div class="text-center mx-auto" style="width: 40vw; min-width: 400px;">
  <form action="{% url 'auctions:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group m-2">
      <input autofocus class="form-control" type="text" name="username" placeholder="Username" />
    </div>
    <div class="form-group m-2">
      <input class="form-control" type="password" name="password" placeholder="Password" />
    </div>
    <input class="btn btn-dark m-2" type="submit" value="Login" />
  </form>
  Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<div class="text-center m-3">
    <h2>Register</h2>
</div>

{% if message %}
<div class="text-center m-2">{{ message }}</div>
{% endif %}

<div class="text-center mx-auto" style="width: 40vw; min-width: 400px;">
    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group m-2">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group m-2">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group m-2">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group m-2">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-dark m-2" type="submit" value="Register">
    </form>
    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
</div>

{% endblock %}

cs50-w/2-commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-center p-2 m-2">Watchlist</h2>

<div class="d-flex flex-wrap justify-content-center">
    {% for listing in user_watchlist %}
    <div class="card m-3" style="width: 19rem;">
        <a href="{% url 'auctions:listings' listing.id %}">
            <img class="card-img-top" src="{{ listing.image_url }}" width="500px">
        </a>
        <div class="card-body m-2">
            <h3>{{ listing.title }}</h3>
            <div class="card-text">
                <p>{{ listing.description }}</p>
                {% if listing.bids_number == 1 %}
                <p>Starting bid: {{ listing.starting_bid }}</p>
                {% else %}
                <p>Current bid: {{ listing.current_bid }}</p>
                {% endif %}
                <p class="blockquote-footer">Published by: {{ listing.user.username }}</p>
                <p class="blockquote-footer">Publication date: {{ listing.pub_date }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}