cs50-w/1-wiki/encyclopedia/urls.py
from . import views

from django.urls import path


app_name = "encyclopedia"
urlpatterns = [
    path("create", views.create, name="create"),
    path("random", views.random_entry, name="random"),
    path("wiki/<str:q>", views.render_entry, name="render_entry"),
    path("wiki/<str:q>/edit", views.edit, name="edit"),
    path("", views.index, name="index")
]

cs50-w/1-wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

cs50-w/1-wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

cs50-w/1-wiki/encyclopedia/forms.py
from . import util
from django import forms
from django.forms.utils import ErrorList


def valid_title(title):
    for entry in util.list_entries():
        if title.lower() == entry.lower():
            return False
    return True


class DivErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self:
            return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<div class="alert alert-danger" role="alert">%s</div>' % e for e in self])


# Forms
class Create(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Content", widget=forms.Textarea(
        attrs={}))

    def clean_title(self):
        data = self.cleaned_data.get('title')
        if not valid_title(data):
            raise forms.ValidationError('The title already exists')
        return data


class Edit(forms.Form):
    content = forms.CharField(label="Content", widget=forms.Textarea(
        attrs={}))


class Search(forms.Form):
    q = forms.CharField(label="", widget=forms.TextInput(
        attrs={'class': 'form-control me-2', 
               'type': 'search', 
               'placeholder': 'Search',
               'aria-label': 'Search',
               'autocomplete': 'off'}))

cs50-w/1-wiki/encyclopedia/views.py
from . import forms
from . import util
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
import markdown2
import random


# Create new encyclopedia entry
def create(request):
    if request.method == "POST":
        form = forms.Create(request.POST, error_class=forms.DivErrorList)
        if form.is_valid():
            content = form.cleaned_data['content']
            title = form.cleaned_data['title']
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:render_entry", kwargs={'q': title}))
        else:
            return render(request, "encyclopedia/create.html", {
                'create': form,
                'search': forms.Search()
            })
    else:
        return render(request, "encyclopedia/create.html", {
            'create': forms.Create(),
            'search': forms.Search()
        })


# Edit an existing encyclopedia entry
def edit(request, q):
    # Submitting form to update an entry (edit the entry)
    if request.method == "POST":
        form = forms.Edit(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(q, content)
            return HttpResponseRedirect(reverse("encyclopedia:render_entry", kwargs={'q': q}))
        else:
            return render(request, "encyclopedia/edit.html", {
                'content': form,
                'search': forms.Search(),
                'title': q
            })
    # Loading the form to edit the entry
    else:
        return render(request, "encyclopedia/edit.html", {
            'content': forms.Edit(initial={'content': util.get_entry(q)}),
            'search': forms.Search(),
            'title': q
        })


# Index page / Search results
def index(request):
    # Search results
    if request.method == "POST":
        form = forms.Search(request.POST)
        if form.is_valid():
            q = form.cleaned_data["q"].lower()
            for entry in util.list_entries():
                if q == entry.lower():
                    return HttpResponseRedirect(reverse("encyclopedia:render_entry", kwargs={'q': entry}))
            return render(request, "encyclopedia/search.html", {
                'entries': list(entry for entry in util.list_entries() if q in entry.lower()),
                'search': forms.Search()
            })
        else:
            return HttpResponseRedirect(reverse("encyclopedia:index"))
    # Index page
    else:
        return render(request, "encyclopedia/index.html", {
            'entries': util.list_entries(),
            'search': forms.Search()
        })


# Random encyclopedia entry
def random_entry(request):
    entry = random.choice(util.list_entries())
    return HttpResponseRedirect(reverse("encyclopedia:render_entry", kwargs={'q': entry}))


# Encyclopedia entry page
def render_entry(request, q):
    for entry in util.list_entries():
        if entry.lower() == q.lower():
            return render(request, "encyclopedia/entry.html", {
                'entry': markdown2.markdown(util.get_entry(entry)),
                'search': forms.Search(),
                'title': entry
            })
    return render(request, "encyclopedia/notfound.html", {
        'search': forms.Search(),
        'title': q
    })

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
New Page
{% endblock %}

{% block body %}
<div class="flex-column text-center">
    <h1>New Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ create.as_p }}
        <input class="btn btn-outline-dark" type="submit" value="Save">
    </form>
</div>
{% endblock %}

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
Edit
{% endblock %}

{% block body %}
<div class="text-center">
    <h1>Editing: {{ title }}</h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {{ content.as_p }}
        <input class="btn btn-outline-dark" type="submit" value="Save" />
    </form>
</div>
{% endblock %}

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
{{ title|safe }}
{% endblock %}

{% block body %}
<div class="text-center">
    {{ entry|safe }}
    <a href="{% url 'encyclopedia:edit' title %}">Edit</a>
</div>
{% endblock %}

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>
<div>
    {% for entry in entries %}
    <div>
        <a href="{% url 'encyclopedia:render_entry' entry %}">{{ entry }}</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'encyclopedia/src/main.png' %}" type="image/png" sizes="128x128" />

    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Miriam+Libre&display=swap" rel="stylesheet">
    <!--Styling-->
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Spline+Sans:wght@400;500;600;700&display=swap"
        rel="stylesheet">
    <link href="{% static 'encyclopedia/style.css' %}" rel="stylesheet">

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Wiki</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'encyclopedia:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'encyclopedia:create' %}">Create New Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'encyclopedia:random' %}">Random Page</a>
                    </li>
                </ul>
                <form class="d-flex" action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ search }}
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container justify-content-center text-center">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</body>

</html>

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
{{ title|safe }}
{% endblock %}

{% block body %}
<div class="container text-center">
    {% load static %}
    <img src="{% static 'encyclopedia/src/pnf.gif' %}" />
    <h1>Page not found</h1>
</div>
{% endblock %}

cs50-w/1-wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>Search results:</h1>

<div>
    {% for entry in entries %}
    <div>
        <a href="{% url 'encyclopedia:render_entry' entry %}">{{ entry }}</a>
    </div>
    {% endfor %}
</div>

{% endblock %}